// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: completion.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkCompletion = `-- name: CheckCompletion :one
SELECT EXISTS (
    SELECT 1
    FROM completion
    WHERE habit_id = $1
        AND user_id = $2
        AND completed_date = CURRENT_DATE
)
`

type CheckCompletionParams struct {
	HabitID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) CheckCompletion(ctx context.Context, arg CheckCompletionParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkCompletion, arg.HabitID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const markCompletion = `-- name: MarkCompletion :exec
INSERT INTO completion (habit_id, user_id, completed_date)
VALUES ($1, $2, CURRENT_DATE)
ON CONFLICT (habit_id, completed_date) DO NOTHING
`

type MarkCompletionParams struct {
	HabitID uuid.UUID
	UserID  uuid.UUID
}

func (q *Queries) MarkCompletion(ctx context.Context, arg MarkCompletionParams) error {
	_, err := q.db.ExecContext(ctx, markCompletion, arg.HabitID, arg.UserID)
	return err
}
