// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (habitName, frequency, category, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, habitName, frequency, category, created_at, updated_at, user_id
`

type CreateHabitParams struct {
	Habitname string
	Frequency string
	Category  sql.NullString
	UserID    uuid.UUID
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, createHabit,
		arg.Habitname,
		arg.Frequency,
		arg.Category,
		arg.UserID,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Habitname,
		&i.Frequency,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM habits
WHERE id = $1
`

func (q *Queries) DeleteHabit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHabit, id)
	return err
}

const getAllHabits = `-- name: GetAllHabits :many
SELECT id, habitname, frequency, category, created_at, updated_at, user_id 
FROM habits
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetAllHabits(ctx context.Context, userID uuid.UUID) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, getAllHabits, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Habitname,
			&i.Frequency,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitByCategory = `-- name: GetHabitByCategory :many
SELECT id, habitname, frequency, category, created_at, updated_at, user_id 
FROM habits
WHERE user_id = $1 
    AND category = $2
ORDER BY created_at ASC
`

type GetHabitByCategoryParams struct {
	UserID   uuid.UUID
	Category sql.NullString
}

func (q *Queries) GetHabitByCategory(ctx context.Context, arg GetHabitByCategoryParams) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, getHabitByCategory, arg.UserID, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Habitname,
			&i.Frequency,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitByID = `-- name: GetHabitByID :one
SELECT id, habitname, frequency, category, created_at, updated_at, user_id
FROM habits
WHERE id = $1
`

func (q *Queries) GetHabitByID(ctx context.Context, id uuid.UUID) (Habit, error) {
	row := q.db.QueryRowContext(ctx, getHabitByID, id)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Habitname,
		&i.Frequency,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const listHabitsWithoutCategory = `-- name: ListHabitsWithoutCategory :many
SELECT id, habitname, frequency, category, created_at, updated_at, user_id
FROM habits
WHERE user_id = $1
    AND category IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListHabitsWithoutCategory(ctx context.Context, userID uuid.UUID) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, listHabitsWithoutCategory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Habitname,
			&i.Frequency,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHabit = `-- name: UpdateHabit :one
UPDATE habits
SET
    habitName = COALESCE($3, habitName),
    frequency = COALESCE($4, frequency),
    category  = COALESCE($5, category),
    updated_at = NOW()
WHERE id = $1
  AND user_id = $2
RETURNING id, habitName, frequency, category, created_at, updated_at, user_id
`

type UpdateHabitParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Habitname sql.NullString
	Frequency sql.NullString
	Category  sql.NullString
}

func (q *Queries) UpdateHabit(ctx context.Context, arg UpdateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, updateHabit,
		arg.ID,
		arg.UserID,
		arg.Habitname,
		arg.Frequency,
		arg.Category,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Habitname,
		&i.Frequency,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}
