// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: habits.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createHabit = `-- name: CreateHabit :one
INSERT INTO habits (habitName, frequency, category, user_id)
VALUES ($1, $2, $3, $4)
RETURNING id, habitName, frequency, category, created_at, updated_at, user_id
`

type CreateHabitParams struct {
	Habitname string
	Frequency string
	Category  sql.NullString
	UserID    uuid.UUID
}

func (q *Queries) CreateHabit(ctx context.Context, arg CreateHabitParams) (Habit, error) {
	row := q.db.QueryRowContext(ctx, createHabit,
		arg.Habitname,
		arg.Frequency,
		arg.Category,
		arg.UserID,
	)
	var i Habit
	err := row.Scan(
		&i.ID,
		&i.Habitname,
		&i.Frequency,
		&i.Category,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const deleteHabit = `-- name: DeleteHabit :exec
DELETE FROM habits
WHERE id = $1
`

func (q *Queries) DeleteHabit(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteHabit, id)
	return err
}

const getAllHabits = `-- name: GetAllHabits :many
SELECT id, habitname, frequency, category, created_at, updated_at, user_id FROM habits
ORDER BY created_at ASC
`

func (q *Queries) GetAllHabits(ctx context.Context) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, getAllHabits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Habitname,
			&i.Frequency,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHabitByCategory = `-- name: GetHabitByCategory :many
SELECT id, habitname, frequency, category, created_at, updated_at, user_id FROM habits
WHERE category = $1
ORDER BY created_at ASC
`

func (q *Queries) GetHabitByCategory(ctx context.Context, category sql.NullString) ([]Habit, error) {
	rows, err := q.db.QueryContext(ctx, getHabitByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Habit
	for rows.Next() {
		var i Habit
		if err := rows.Scan(
			&i.ID,
			&i.Habitname,
			&i.Frequency,
			&i.Category,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
